name: ci

on:
  push: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure Docker credentials
        run: doctl registry login

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          repository: registry.digitalocean.com/jonahgeorge/cross-gambling
          tag_with_ref: true
          add_git_labels: true
