name: ci

on:
  push: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure Docker credentials
        run: doctl registry login

      - name: Build image
        run: docker build -t registry.digitalocean.com/jonahgeorge/cross-gambling:$(echo $GITHUB_SHA | head -c7) .

      - name: Push image
        run: docker push registry.digitalocean.com/jonahgeorge/cross-gambling
      
      - name: Update terraform var
        run: terraform apply -var="cross_gambling_image_tag=$(echo $GITHUB_SHA | head -c7)"
